apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  annotations:
    # Image updater annotations
    argocd-image-updater.argoproj.io/image-list: josenetoalest/hello-world
    argocd-image-updater.argoproj.io/josenetoalest/hello-world.update-strategy: digest
    argocd-image-updater.argoproj.io/josenetoalest/hello-world.allow-tags: sha-*
spec:
  project: default
  source:
    repoURL: https://github.com/josenetoo/demo-hello-world-app.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
